/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.SwingUtilities;

/**
 *
 * @author ferna
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCargarXML = new javax.swing.JButton();
        btnListaXML = new javax.swing.JButton();
        btnComprobarPlagio = new javax.swing.JButton();
        btnListaReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarXML.setText("Cargar XML");
        btnCargarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarXMLActionPerformed(evt);
            }
        });

        btnListaXML.setText("Lista de XML");
        btnListaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaXMLActionPerformed(evt);
            }
        });

        btnComprobarPlagio.setText("Comprobar Plagio");
        btnComprobarPlagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarPlagioActionPerformed(evt);
            }
        });

        btnListaReportes.setText("Lista de Reportes");
        btnListaReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarXML)
                    .addComponent(btnComprobarPlagio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListaXML)
                    .addComponent(btnListaReportes))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarXML)
                    .addComponent(btnListaXML))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprobarPlagio)
                    .addComponent(btnListaReportes))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarXMLActionPerformed

            Vista_CargaXML vistaCargarXML = new Vista_CargaXML();
            vistaCargarXML.setVisible(true);
    }//GEN-LAST:event_btnCargarXMLActionPerformed

    private void btnListaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaXMLActionPerformed
            Vista_ListaXML vistaListaXML = new Vista_ListaXML();
            vistaListaXML.setVisible(true);
    }//GEN-LAST:event_btnListaXMLActionPerformed

    private void btnComprobarPlagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarPlagioActionPerformed
            Vista_ComprobarPlagio vistaComprobarPlagio = new Vista_ComprobarPlagio();
            vistaComprobarPlagio.setVisible(true);
    }//GEN-LAST:event_btnComprobarPlagioActionPerformed

    private void btnListaReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaReportesActionPerformed
            Vista_ListaReportes vistaListaReportes = new Vista_ListaReportes();
            vistaListaReportes.setVisible(true);
    }//GEN-LAST:event_btnListaReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarXML;
    private javax.swing.JButton btnComprobarPlagio;
    private javax.swing.JButton btnListaReportes;
    private javax.swing.JButton btnListaXML;
    // End of variables declaration//GEN-END:variables
}
